export { default as Dashboard } from './Dashboard';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Modules } from './Modules';
export { default as Notfound } from './Not-found';
export { default as Landing } from './Landing';
export { default as Courses } from './Courses';
export { default as Profile } from './Profile';
export { default as Students } from './Students';
